# Generated by Django 2.2.13 on 2025-06-05 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fac', '0003_auto_20190831_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaenc',
            name='cantidad_cuotas',
            field=models.IntegerField(default=1, help_text='Número de cuotas si es a crédito'),
        ),
        migrations.AddField(
            model_name='facturaenc',
            name='dias_vencimiento_irregular',
            field=models.CharField(blank=True, help_text="Lista de días para vencimientos irregulares (ej: '30,60,90')", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='facturaenc',
            name='tipo_pago',
            field=models.CharField(choices=[('CO', 'Contado'), ('CR', 'Crédito')], default='CO', help_text='Tipo de pago: Contado o Crédito', max_length=2),
        ),
        migrations.AddField(
            model_name='facturaenc',
            name='tipo_vencimiento',
            field=models.CharField(choices=[('RE', 'Regular'), ('IR', 'Irregular')], default='RE', help_text='Tipo de vencimiento de cuotas: Regular o Irregular', max_length=2),
        ),
        migrations.AlterField(
            model_name='facturadet',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='facturadet',
            name='uc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facturadet',
            name='um',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('numero_cuota', models.IntegerField(default=1)),
                ('importe', models.FloatField(default=0)),
                ('fecha_vencimiento', models.DateField()),
                ('cobrado', models.BooleanField(default=False)),
                ('fecha_cobro', models.DateField(blank=True, null=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fac.FacturaEnc')),
                ('uc', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('um', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas por Cobrar/Pagar',
                'unique_together': {('factura', 'numero_cuota')},
            },
        ),
    ]
