# Generated by Django 2.2.13 on 2025-06-13 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0004_auto_20250605_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('NA', 'Natural'), ('JU', 'Jurídica')], default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='fac.FacturaEnc'),
        ),
        migrations.AlterField(
            model_name='facturaenc',
            name='tipo_pago',
            field=models.CharField(choices=[('CO', 'Contado'), ('CR', 'Crédito')], default='CO', help_text='Tipo de pago: Contado o Crédito', max_length=10),
        ),
        migrations.AlterField(
            model_name='facturaenc',
            name='tipo_vencimiento',
            field=models.CharField(choices=[('RE', 'Regular'), ('IR', 'Irregular')], default='RE', help_text='Tipo de vencimiento de cuotas: Regular o Irregular', max_length=10),
        ),
    ]
